ALTER TABLE events ADD COLUMN cover_image TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN hero_image TEXT NOT NULL DEFAULT '';
ALTER TABLE events ADD COLUMN detail_images TEXT NOT NULL DEFAULT '';
