const {layoutTicket,drawTicket}=require('../../utils/ticket-poster');
const {groupBookings,experienceRows,activityStatus}=require('../../utils/booking-groups');
const {request,login}=require('../../utils/api');
const labels={confirmed:'预约成功',checked:'已核销',cancelled:'已取消',published:'预约中',draft:'草稿',ended:'已结束'};
const decorate=b=>({...b,descriptionLines:String(b.description||'').split(/\r?\n/).map(text=>({text,heading:/^[①-⑳]/.test(text.trim())})),detailImageList:(b.detail_images||'').split('\n').filter(Boolean),label:labels[b.status],maskedPhone:(b.phone||'').replace(/(\d{3})\d{4}(\d{4})/,'$1****$2')});
Page({data:{splashSkipTop:100,posterReady:false,slides:[],splash:null,splashRemaining:0,view:'home',tab:'events',filter:'all',events:[],visibleEvents:[],bookings:[],visibleBookings:[],event:null,eventBooked:false,bookingStatusLoading:false,booking:null,sheet:'',participationModes:[],participationConfig:[],selectedModeKind:'',participationIndex:-1,selectionCards:[],experienceChoices:[],selectedExperienceIds:[],selectedSlotIds:[],selectionReady:false,types:[],dates:[],times:[],selectedType:'',selectedDate:'',slotId:'',selectedTime:'',isFull:false,name:'',phone:'',gender:'女',genders:['女','男','不便透露'],terms:false,photo:false,busy:false,demo:false,changing:false,qr:null},
async onLoad(options){this.updateSplashPosition();try{const config=await request('config');getApp().globalData.config=config;this.setData({demo:config.demo});await this.refresh();this.homeLoaded=true;await this.loadContent(!options.event&&!options.booking&&!options.mine);if(options.mine)await this.loadMine();if(options.event)await this.openEventId(options.event);if(options.booking){await login();const bookings=await request('bookings');const booking=bookings.find(b=>b.id===options.booking);if(booking)await this.showBooking(booking)}}catch(e){this.error(e)}},
updateSplashPosition(){
 let top=100;
 try{
  const info=wx.getWindowInfo?wx.getWindowInfo():wx.getSystemInfoSync();
  const status=info.statusBarHeight||20;
  const menu=wx.getMenuButtonBoundingClientRect();
  top=Math.max(status+44,menu&&menu.height>0?menu.top+menu.height:0)+12;
 }catch(e){console.warn('开屏按钮位置使用默认值')}
 this.setData({splashSkipTop:top});
},
onResize(){this.updateSplashPosition()},
async loadContent(showSplash){try{const c=await request('content');this.setData({slides:Array.isArray(c.slides)?c.slides:[]});if(showSplash&&this.data.view==='home'&&c.splash?.image){this.skipSplash();const seconds=Math.min(10,Math.max(1,Number(c.splash.duration)||3));this.splashDeadline=Date.now()+seconds*1000;this.setData({splash:c.splash,splashRemaining:seconds});this.splashTimer=setInterval(()=>{const n=Math.ceil((this.splashDeadline-Date.now())/1000);if(n<=0)this.skipSplash();else this.setData({splashRemaining:n})},250);this.splashTimeout=setTimeout(()=>this.skipSplash(),seconds*1000)}}catch(e){this.skipSplash();console.warn('首页内容加载失败',e)}},
skipSplash(){clearInterval(this.splashTimer);clearTimeout(this.splashTimeout);this.setData({splash:null,splashRemaining:0})},
onHide(){this.skipSplash();wx.hideLoading()},
onUnload(){clearInterval(this.splashTimer);clearTimeout(this.splashTimeout);wx.hideLoading()},
contentTap(e){const id=e.currentTarget.dataset.event;this.skipSplash();if(id)this.openEventId(id).catch(e=>this.error(e))},
navigationBack(){if(this.data.view==='ticket')this.loadMine();else this.home()},
onShow(){if(!this.openingEvent)wx.hideLoading();if(this.data.view==='mine')this.loadMine();else if(this.data.view==='detail')this.refreshEventBooking().catch(e=>this.error(e));else if(this.homeLoaded&&this.data.view==='home'){this.refresh().catch(e=>this.error(e));this.loadContent(false)}},
async onPullDownRefresh(){try{await this.refresh();if(this.data.view==='mine')await this.loadMine();else if(this.data.view==='detail')await this.refreshEventBooking()}catch(e){this.error(e)}finally{wx.stopPullDownRefresh()}},
error(e){wx.showToast({title:e.message||'操作失败，请重试',icon:'none',duration:3000})},
async refresh(){const events=(await request('events')).map(decorate);this.setData({events});this.applyFilter()},
applyFilter(){const {filter,events,bookings}=this.data;const groups=groupBookings(bookings).map(group=>{const status=activityStatus(group.items);return {...group,activityStatus:status,activityLabel:status==='ongoing'?'进行中':'已核销',dates:[...new Set(group.items.map(b=>b.date))].join('、')}});this.setData({visibleEvents:events.filter(e=>filter==='all'||e.status===filter),visibleBookings:groups.filter(group=>group.activityStatus!=='inactive'&&(filter==='all'||group.activityStatus===filter))})},
setFilter(e){this.setData({filter:e.currentTarget.dataset.value});this.applyFilter()},
home(){this.skipSplash();wx.hideLoading();this.setData({posterReady:false,view:'home',tab:'events',event:null,booking:null,filter:'all',sheet:''});this.refresh().catch(e=>this.error(e))},
async loadMine(){try{const filter=this.data.view==='mine'?this.data.filter:'ongoing';await login();const [rows]=await Promise.all([request('bookings'),this.loadContent(false)]);const bookings=rows.map(decorate);this.setData({bookings,view:'mine',tab:'mine',event:null,booking:null,filter});this.applyFilter()}catch(e){this.error(e)}},
async openEvent(e){try{await this.openEventId(e.currentTarget.dataset.id)}catch(err){this.error(err)}},
async openEventId(id){if(this.openingEvent)return;if(!id)throw new Error('活动不存在，请刷新后重试');this.openingEvent=true;wx.showLoading({title:'加载活动',mask:false});try{const event=await request('events/'+encodeURIComponent(id));if(!event||!event.id)throw new Error('活动信息加载失败');const slots=Array.isArray(event.slots)?event.slots:[];this.skipSplash();this.setData({event:decorate({...event,slots}),eventBooked:false,view:'detail',booking:null,changing:false,sheet:'',types:[],dates:[],times:[],slotId:''});await this.refreshEventBooking();}finally{this.openingEvent=false;wx.hideLoading()}},
async refreshEventBooking(){
 const id=this.data.event?.id;if(!id||this.data.view!=='detail')return;
 const revision=(this.bookingStatusRevision||0)+1;this.bookingStatusRevision=revision;
 this.setData({bookingStatusLoading:true});
 try{await login();const bookings=await request('bookings');if(this.bookingStatusRevision!==revision||this.data.event?.id!==id||this.data.view!=='detail')return;
 this.setData({eventBooked:bookings.some(b=>b.event_id===id&&b.status!=='cancelled')});
 }finally{if(this.bookingStatusRevision===revision)this.setData({bookingStatusLoading:false})}
},
prepareSlots(){
 const config=(this.data.event.participation_modes||[]).filter(m=>m.enabled&&this.data.event.slots.some(s=>s.mode_id===m.id));
 const modes=config.map(m=>m.name);
 this.setData({participationConfig:config,participationModes:modes,participationLabels:['请选择参与方式',...modes],participationIndex:-1,selectionCards:[],experienceChoices:[],selectedExperienceIds:[],selectedSlotIds:[],selectionReady:false,slotId:'',isFull:false,selectedModeKind:''});
 if(this.data.changing){const slot=this.data.event.slots.find(s=>s.id===this.data.booking.slot_id);this.setData({participationIndex:config.findIndex(m=>m.id===slot?.mode_id)});if(this.data.participationIndex>=0)this.buildSelectionCards();}

},
participationChange(e){this.setData({participationIndex:Number(e.detail.value)-1});if(this.data.participationIndex<0){this.setData({selectionCards:[],experienceChoices:[],selectedModeKind:''});this.updateSelection();return}this.buildSelectionCards()},
buildSelectionCards(){
 const mode=this.data.participationConfig[this.data.participationIndex];if(!mode)return;
 const slots=this.data.event.slots.filter(s=>s.mode_id===mode.id);
 const direct=mode.kind==='direct';
 const dates=[...new Set(slots.map(s=>s.date))].sort().map(date=>({value:date,label:date.slice(5).replace('-','月')+'日'}));
 const selectedIds=this.data.changing?(this.data.bookingSiblings||[this.data.booking]).flatMap(x=>JSON.parse(x.experience_ids||'[]')):[];
 const experienceChoices=direct?[]:mode.items.map(x=>{const lines=x.name.replace(/\r\n?/g,'\n').split('\n');return {...x,title:lines[0],description:lines.slice(1).join('\n'),selected:selectedIds.includes(x.id),slotId:''}});
 this.setData({selectionCards:[{name:mode.name,label:mode.name,slotIds:slots.map(s=>s.id),selected:true,dates,date:'',times:[],slotId:''}],experienceChoices,selectedModeKind:mode.kind});this.updateSelection();
},
toggleExperience(e){const i=Number(e.currentTarget.dataset.index);this.setData({experienceChoices:this.data.experienceChoices.map((x,n)=>n===i?{...x,selected:!x.selected,slotId:''}:x)});this.updateSelection()},
chooseCardDate(e){const i=Number(e.currentTarget.dataset.index),date=e.currentTarget.dataset.value;const cards=this.data.selectionCards.map((c,n)=>n===i?{...c,date,slotId:'',times:this.data.event.slots.filter(s=>c.slotIds.includes(s.id)&&s.date===date).map(s=>({...s,full:s.booked-(this.data.changing&&(this.data.bookingSiblings||[]).some(b=>b.slot_id===s.id&&['confirmed','checked'].includes(b.status))?1:0)>=s.capacity,past:new Date(`${s.date}T${s.time.split('-')[0]}:00+08:00`).getTime()<=Date.now()}))}:c);this.setData({selectionCards:cards,experienceChoices:this.data.experienceChoices.map(x=>({...x,slotId:''}))});this.updateSelection()},
chooseCardTime(e){const i=Number(e.currentTarget.dataset.index),id=e.currentTarget.dataset.id;const card=this.data.selectionCards[i];if(!card.times.some(s=>s.id===id&&!s.past&&!s.full))return;this.setData({selectionCards:this.data.selectionCards.map((c,n)=>n===i?{...c,slotId:id}:c)});this.updateSelection()},
chooseExperienceTime(e){const i=Number(e.currentTarget.dataset.experience),id=e.currentTarget.dataset.id,card=this.data.selectionCards[0];if(!card?.times.some(s=>s.id===id&&!s.past&&!s.full&&(s.experience_id===this.data.experienceChoices[i]?.id)))return;this.setData({experienceChoices:this.data.experienceChoices.map((x,n)=>n===i?{...x,selected:true,slotId:id}:x)});this.updateSelection()},
updateSelection(){const card=this.data.selectionCards[0],selected=this.data.experienceChoices.filter(x=>x.selected),isExperience=this.data.selectedModeKind==='experiences';const selections=isExperience?selected.map(x=>({slotId:x.slotId,experienceIds:[x.id]})):card?.slotId?[{slotId:card.slotId,experienceIds:[]}]:[];const ids=[...new Set(selections.map(x=>x.slotId).filter(Boolean))];this.setData({experienceChoices:this.data.experienceChoices.map(x=>({...x,times:(card?.times||[]).filter(s=>s.experience_id===x.id)})),selectedExperienceIds:selected.map(x=>x.id),selectedSlotIds:ids,selectedSelections:selections,slotId:ids[0]||'',selectionReady:selections.length>0&&selections.every(x=>!!x.slotId),isFull:!!card?.times.some(s=>ids.includes(s.id)&&s.full)})},
async reserve(){try{if(this.data.eventBooked||this.data.bookingStatusLoading||this.data.event?.status!=='published')return;const id=this.data.event.id;await this.refreshEventBooking();if(this.data.view!=='detail'||this.data.event?.id!==id||this.data.eventBooked)return;if(!this.data.event?.slots?.length)return this.error(new Error('该活动暂未配置可预约场次'));this.prepareSlots();this.setData({sheet:'slots'})}catch(e){this.error(e)}},
closeSheet(){if(!this.data.busy)this.setData({sheet:''})},
noop(){},
async confirmSlot(){if(this.data.busy)return;if(!this.data.selectionReady)return this.error(new Error('请选择日期，并为所选体验选择时间'));if(!this.data.changing){this.setData({busy:true});wx.navigateTo({url:'/pages/register/register?event='+encodeURIComponent(this.data.event.id)+'&slots='+encodeURIComponent(JSON.stringify(this.data.selectedSlotIds))+'&experiences='+encodeURIComponent(JSON.stringify(this.data.selectedExperienceIds))+'&selections='+encodeURIComponent(JSON.stringify(this.data.selectedSelections)),success:()=>this.setData({sheet:''}),complete:()=>this.setData({busy:false}),fail:()=>this.error(new Error('无法打开报名页面，请重试'))});return}this.setData({busy:true});try{const b=await request('bookings/'+this.data.booking.id+'/reschedule',{selections:this.data.selectedSelections});this.setData({sheet:'',changing:false});await this.showBooking(b)}catch(e){this.error(e)}finally{this.setData({busy:false})}},
async selectBooking(e){const b=this.data.bookings.find(b=>b.id===e.currentTarget.dataset.id);await this.showBooking(b)},
async showBooking(b){if(!b)return;let siblings=[decorate(b)];try{const bookings=(await request('bookings')).map(decorate);this.setData({bookings});siblings=groupBookings(bookings).find(g=>g.items.some(x=>x.id===b.id))?.items||siblings}catch(e){this.error(e)}const current=siblings.find(x=>x.id===b.id)||decorate(b),active=siblings.filter(x=>['confirmed'].includes(x.status));this.setData({booking:current,bookingSiblings:siblings,bookingExperienceRows:experienceRows(siblings),view:'ticket',sheet:'',qr:null,ticketQROpen:false,hasAdmission:siblings.some(x=>['confirmed','checked'].includes(x.status)),canManageActivity:active.length>0,activityBookingTitle:siblings.every(x=>x.status==='cancelled')?'预约已取消':siblings.every(x=>x.status==='checked')?'活动已核销':'报名成功！'})},
async openTicketQR(e){const id=e?.currentTarget?.dataset?.id;const b=id?this.data.bookingSiblings.find(x=>x.id===id):this.data.bookingSiblings.find(x=>['confirmed','checked'].includes(x.status));if(!b)return;this.setData({ticketQROpen:true,qrBooking:b,qr:null});try{const t=await request('bookings/'+b.id+'/ticket');if(!this.data.ticketQROpen||this.data.qrBooking.id!==b.id)return;this.setData({qr:t.qr},()=>this.drawQR(t.qr))}catch(e){this.setData({ticketQROpen:false});this.error(e)}},
closeTicketQR(){this.setData({ticketQROpen:false,qr:null})},
changeActivitySlot(){return this.reschedule()},
drawQR(qr){const ctx=wx.createCanvasContext('ticketQR',this);const size=220;ctx.setFillStyle('#ffffff');ctx.fillRect(0,0,size,size);const cell=size/(qr.size+8);ctx.setFillStyle('#1A4D3F');qr.data.forEach((v,i)=>{if(v)ctx.fillRect((i%qr.size+4)*cell,(Math.floor(i/qr.size)+4)*cell,cell+.3,cell+.3)});ctx.draw()},
async cancel(){const r=await new Promise(resolve=>wx.showModal({title:'取消本次活动预约？',content:'本次活动预约下的所有体验将一并取消，各场次名额将释放，可供其他嘉宾预约。',cancelText:'确认取消',confirmText:'再想想',success:resolve}));if(!r.cancel)return;try{const target=this.data.bookingSiblings.find(x=>['confirmed'].includes(x.status))||this.data.booking;const b=await request('bookings/'+target.id+'/cancel',{});await this.showBooking(b)}catch(e){this.error(e)}},
async reschedule(e){const id=e?.currentTarget?.dataset?.id;if(id){const selected=this.data.bookingSiblings.find(x=>x.id===id);if(selected)this.setData({booking:selected})}try{const event=await request('events/'+this.data.booking.event_id);this.setData({event,changing:true,sheet:'slots'});this.prepareSlots()}catch(e){this.error(e)}},
subscribe(){const config=getApp().globalData.config;const id=config?.subscriptionTemplateId;if(!id)return this.error(new Error('订阅通知尚未配置，请在我的活动查看最新状态'));wx.requestSubscribeMessage({tmplIds:[id],success:async r=>{if(r[id]==='accept'){try{await request('bookings/'+this.data.booking.id+'/subscribe',{});wx.showToast({title:'订阅授权成功',icon:'none'})}catch(e){this.error(e)}}else wx.showToast({title:'可在我的活动查看',icon:'none'})},fail:e=>this.error(new Error(e.errMsg))})},
copyTicketCode(){if(this.data.qr&&this.data.booking.code)wx.setClipboardData({data:'HG:'+(this.data.qrBooking||this.data.booking).code})},
previewContact(){const url=this.data.booking?.contact_qr;if(!url)return;wx.previewImage({current:url,urls:[url],showmenu:true,fail:()=>this.error(new Error('二维码预览失败，请重试'))})},
copyContact(){wx.setClipboardData({data:this.data.booking.contact_wechat})},
saveContact(){wx.getImageInfo({src:this.data.booking.contact_qr,success:r=>wx.saveImageToPhotosAlbum({filePath:r.path,success:()=>wx.showToast({title:'已保存'}),fail:()=>wx.showModal({title:'无法保存图片',content:'请在设置中允许保存到相册后重试。',confirmText:'打开设置',success:r=>{if(r.confirm)wx.openSetting({})}})}),fail:()=>this.error(new Error('客服二维码加载失败，请重试'))})},
saveTicket(){if(!this.data.qr||this.savingPoster)return;this.savingPoster=true;const measure=wx.createCanvasContext('poster',this);const booking=this.data.qrBooking||this.data.booking;this.ticketPosterPlan=layoutTicket({booking,experiences:this.data.bookingExperienceRows||experienceRows(this.data.bookingSiblings||[booking]),qr:this.data.qr},(text,size)=>{measure.setFontSize(size);return measure.measureText(text).width});this.setData({posterHeight:this.ticketPosterPlan.height,posterReady:true},()=>this.renderTicketPoster())},
renderTicketPoster(){const plan=this.ticketPosterPlan;if(!plan){this.savingPoster=false;this.setData({posterReady:false});return}const ctx=wx.createCanvasContext('poster',this);drawTicket(ctx,plan);ctx.draw(false,()=>{const scale=plan.height>4000?1:2;wx.canvasToTempFilePath({canvasId:'poster',width:plan.width,height:plan.height,destWidth:plan.width*scale,destHeight:plan.height*scale,complete:()=>{this.savingPoster=false;this.ticketPosterPlan=null;this.setData({posterReady:false})},success:r=>wx.saveImageToPhotosAlbum({filePath:r.tempFilePath,success:()=>wx.showToast({title:'入场凭证已保存'}),fail:()=>wx.showModal({title:'保存相册失败',content:'请在设置中允许保存到相册后重试。',confirmText:'打开设置',success:r=>{if(r.confirm)wx.openSetting({})}})}),fail:()=>this.error(new Error('生成凭证失败，请重试'))},this)})},
showTerms(e){wx.navigateTo({url:'/pages/terms/terms?type='+encodeURIComponent(e.currentTarget.dataset.type||'terms')})},
backTerms(){this.setData({sheet:this.data.previousSheet||''})},
onShareAppMessage(){return {title:this.data.event?.title||'蜜金 · 海岛漫游记',path:'/pages/index/index'+(this.data.event?'?event='+this.data.event.id:'')}}
});
