'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function AdminUsers(){
 const [data,setData]=useState<any>({users:[],currentId:''}),[modal,setModal]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){try{setData(await api('admin/users'))}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[]);
 async function status(user:any){if(busy)return;setBusy(true);setError('');try{await api('admin/users/status',{id:user.id,enabled:!user.enabled});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=Object.fromEntries(new FormData(e.currentTarget));if(f.password!==f.confirm){setError('两次输入的密码不一致');return}setBusy(true);setError('');try{const r=await api(modal.id?'admin/users/password':'admin/users',{...f,id:modal.id});if(r.relogin){localStorage.removeItem('hg_admin');window.location.replace('/login');return}setModal(null);setMessage(modal.id?'密码已修改，该账号需重新登录':'账号已创建');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><div className="toolbar"><Button className="primary" onClick={()=>{setError('');setModal({})}}>新增用户</Button><span role="status">{message}</span></div>{error&&!modal&&<div className="alert">{error}</div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>登录账号</th><th>权限</th><th>状态</th><th>创建日期</th><th>操作</th></tr></thead><tbody>{data.users.map((u:any)=><tr key={u.id}><td>{u.username}{u.id===data.currentId&&<small>当前账号</small>}</td><td>后台管理员</td><td>{u.enabled?'启用':'停用'}</td><td>{u.created_at.slice(0,10)}</td><td><Button variant="ghost" onClick={()=>{setError('');setModal(u)}}>修改密码</Button><Button variant="ghost" disabled={busy||u.id===data.currentId} onClick={()=>status(u)}>{u.enabled?'停用':'启用'}</Button></td></tr>)}</tbody></table></div></section><Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy){setModal(null);setError('')}}}><DialogContent><DialogTitle>{modal?.id?'修改密码':'新增用户'}</DialogTitle><DialogDescription>{modal?.id?`修改 ${modal.username} 的登录密码，原登录会话将失效。`:'创建可登录运营后台的管理员账号。'}</DialogDescription>{error&&<div className="alert">{error}</div>}<form className="form-grid" onSubmit={save}>{!modal?.id&&<label className="field">账号<Input name="username" required minLength={3} maxLength={40} pattern="[a-zA-Z0-9_-]+" autoComplete="off" /></label>}{modal?.id===data.currentId&&<label className="field">当前密码<Input name="oldPassword" type="password" required maxLength={128} autoComplete="current-password" /></label>}<label className="field">新密码<Input name="password" type="password" required minLength={5} maxLength={128} autoComplete="new-password" /></label><label className="field">确认密码<Input name="confirm" type="password" required minLength={5} maxLength={128} autoComplete="new-password" /></label><Button type="submit" className="primary" disabled={busy}>{busy?'保存中…':'保存'}</Button></form></DialogContent></Dialog></>;
}
