'use client';
import {useState} from 'react';
import {api} from '@/lib/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export default function ExperienceManager({items,refresh,eventId}:{items:any[],refresh:()=>Promise<void>,eventId:string}){
 const [editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(value:any){setBusy(true);setMessage('');try{await api('admin/experiences',{...value,eventId});await refresh();setEditing(null);setMessage('体验已保存');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function remove(item:any){if(!window.confirm('确认删除体验「'+item.name+'」？有关联场次的体验不能删除。'))return;setBusy(true);setMessage('');try{await api('admin/experiences/delete',{id:item.id,eventId});await refresh();setEditing(null);setMessage('体验已删除')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="panel" style={{padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>体验管理</h2><Button disabled={busy} onClick={()=>{setMessage('');setEditing({name:'',enabled:true})}}>新增体验</Button></div><p className="muted" style={{margin:'16px 0'}}>改名会同步更新关联场次及预约中显示的名称。停用后不可用于新场次，已有场次和预约保持有效。未设置体验的活动可直接新增场次，用户只需选择日期和时间。</p>{message&&<p role="status">{message}</p>}{editing&&<form onSubmit={e=>{e.preventDefault();void save(editing)}} style={{display:'grid',gap:16,padding:20,background:'#f7f8f5',marginBottom:20}}><label>体验名称<Input value={editing.name} maxLength={80} required onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label><input type="checkbox" checked={!!editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/> 启用</label><div style={{display:'flex',gap:12}}><Button type="submit" disabled={busy}>{busy?'保存中…':'保存体验'}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditing(null)}>取消</Button></div></form>}<div className="table-wrap"><table><thead><tr><th>体验名称</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.enabled?'已启用':'已停用'}</td><td><Button variant="ghost" disabled={busy} onClick={()=>{setMessage('');setEditing({...item,enabled:!!item.enabled})}}>编辑</Button><Button variant="ghost" disabled={busy} onClick={()=>void save({...item,enabled:!item.enabled})}>{item.enabled?'停用':'启用'}</Button><Button variant="ghost" disabled={busy} onClick={()=>void remove(item)}>删除</Button></td></tr>)}</tbody></table></div></section>
}
