const {request,login}=require('../../utils/api');
Page({
data:{selectedSlots:[],selections:[],experienceIds:[],selectedExperienceNames:'',slotIds:[],reservations:[],booking:null,successOpen:false,successTitle:'报名成功',successNote:'',event:null,slotId:'',selectedType:'',selectedDate:'',selectedTime:'',isFull:false,name:'',phone:'',birthday:'',today:'',gender:'',genders:['请选择性别','女','男','不便透露'],terms:false,photo:false,demo:false,busy:false,sheet:'',errorMessage:''},
async onLoad(options){this.setData({today:new Date(Date.now()+8*3600000).toISOString().slice(0,10)});try{await login();const [event,config]=await Promise.all([request('events/'+encodeURIComponent(options.event||'')),request('config')]);getApp().globalData.config=config;const identity=await request('auth/me');this.setData({phone:identity.phone||''});const ids=options.slots?JSON.parse(decodeURIComponent(options.slots)):[options.slot];if(!Array.isArray(ids)||!ids.length)throw Error('请选择场次');let selectedSlots=ids.map(id=>event.slots.find(s=>s.id===id));if(selectedSlots.some(s=>!s))throw Error('场次不存在，请返回重新选择');const slot=selectedSlots[0];const experienceIds=options.experiences?JSON.parse(decodeURIComponent(options.experiences)):[];const mode=(event.participation_modes||[]).find(m=>m.id===slot.mode_id);const selectedExperienceNames=(mode?.items||[]).filter(x=>experienceIds.includes(x.id)).map(x=>x.name).join('、');const selections=options.selections?JSON.parse(decodeURIComponent(options.selections)):[{slotId:slot.id,experienceIds}];if(!Array.isArray(selections)||!selections.length)throw Error('请选择体验和时间');selectedSlots=selections.map((selection,index)=>{const chosen=event.slots.find(x=>x.id===selection.slotId);if(!chosen)throw Error('场次不存在，请返回重新选择');return {...chosen,selectionKey:String(index),experience_label:selection.experienceIds.length?(mode?.items||[]).filter(x=>selection.experienceIds.includes(x.id)).map(x=>x.name).join('、'):chosen.experience_label}});this.setData({event,selections,experienceIds,selectedExperienceNames,demo:config.demo,slotIds:ids,selectedSlots,slotId:slot.id,selectedType:slot.experience,selectedDate:slot.date,selectedTime:slot.time,isFull:selectedSlots.some(s=>s.booked>=s.capacity)})}catch(e){this.setData({errorMessage:e.message||'报名信息加载失败'})}},
navigationBack(){if(this.data.booking)return this.viewBooking();if(getCurrentPages().length>1)wx.navigateBack();else wx.reLaunch({url:'/pages/index/index'})},
error(e){wx.showToast({title:e.message||'操作失败，请重试',icon:'none',duration:3000})},
input(e){this.setData({[e.currentTarget.dataset.field]:e.detail.value})},
genderChange(e){const i=Number(e.detail.value);this.setData({gender:i?this.data.genders[i]:''})},
birthdayChange(e){this.setData({birthday:e.detail.value})},
consent(e){this.setData({terms:e.detail.value.includes('terms'),photo:e.detail.value.includes('photo')})},
async getPhone(e){if(!e.detail.code)return this.error(new Error('需同意授权手机号后完成预约'));try{const r=await request('phone',{code:e.detail.code});this.setData({phone:r.phone})}catch(err){this.error(err)}},
async submit(){if(this.data.booking){this.setData({successOpen:true});return}if(this.data.busy)return;const d=this.data;if(!d.terms)return this.error(new Error('请阅读并同意预约条款'));if(!d.name.trim()||!/^1[3-9]\d{9}$/.test(d.phone))return this.error(new Error('请填写姓名和有效手机号'));if(!d.birthday)return this.error(new Error('请选择生日'));if(!['女','男','不便透露'].includes(d.gender))return this.error(new Error('请选择性别'));this.setData({busy:true});try{const booking=await request('bookings',{selections:d.selections,name:d.name.trim(),phone:d.phone,gender:d.gender,birthday:d.birthday,terms:d.terms,photoConsent:d.photo});const reservations=booking.reservations||[booking];this.setData({booking,reservations,successOpen:true,successTitle:'报名成功',successNote:''})}catch(e){this.error(e)}finally{this.setData({busy:false})}},
closeSuccess(){this.setData({successOpen:false})},
viewBooking(){const booking=this.data.booking;if(!booking)return;const pages=getCurrentPages(),previous=pages[pages.length-2];if(previous&&previous.showBooking){wx.navigateBack({success:()=>previous.showBooking(booking)})}else wx.reLaunch({url:'/pages/index/index?booking='+encodeURIComponent(booking.id)})},
onShareAppMessage(){const event=this.data.event;return {title:event?.title?'邀请你一起探索 · '+event.title:'邀请你一起探索蜜金活动',path:'/pages/index/index'+(event?.id?'?event='+encodeURIComponent(event.id):''),...(event?.cover_image?{imageUrl:event.cover_image}:{})}},
showTerms(e){wx.navigateTo({url:'/pages/terms/terms?type='+encodeURIComponent(e.currentTarget.dataset.type||'terms')})},closeSheet(){this.setData({sheet:''})},noop(){}
});
